### ISSUE TITLE
Unable to open serial port

### ISSUE THREAD

**Issue by IgorGanapolsky** [zsmartsystems/com.zsmartsystems.zigbee.sniffer#23]
❯ java -jar ZigBeeSniffer.jar -port /dev/tty.SLAB_USBtoUART -baud 115200 -flow hardware
> NCP initialisation starting...
Opened serial port /dev/tty.SLAB_USBtoUART at 115200
DEBUG  11:41:32.972  Opening port /dev/tty.SLAB_USBtoUART at 115200 baud with FLOWCONTROL_OUT_RTSCTS.
ERROR  11:41:32.979  Error opening serial port.
jssc.SerialPortException: Port name - /dev/tty.SLAB_USBtoUART; Method name - openPort(); Exception type - Port not found.
        at jssc.SerialPort.openPort(SerialPort.java:167)
        at com.zsmartsystems.zigbee.serial.ZigBeeSerialPort.openSerialPort(ZigBeeSerialPort.java:133)
        at com.zsmartsystems.zigbee.serial.ZigBeeSerialPort.open(ZigBeeSerialPort.java:96)
        at com.zsmartsystems.zigbee.serial.ZigBeeSerialPort.open(ZigBeeSerialPort.java:90)
        at com.zsmartsystems.zigbee.dongle.ember.ZigBeeDongleEzsp.initialiseEzspProtocol(ZigBeeDongleEzsp.java:1216)
        at com.zsmartsystems.zigbee.dongle.ember.ZigBeeDongleEzsp.getEmberMfglib(ZigBeeDongleEzsp.java:384)
        at com.zsmartsystems.zigbee.sniffer.ZigBeeSniffer.initialiseNcp(ZigBeeSniffer.java:425)
        at com.zsmartsystems.zigbee.sniffer.ZigBeeSniffer.main(ZigBeeSniffer.java:254)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
WARN   11:41:32.981  Unable to open serial port: Failed to open serial port: /dev/tty.SLAB_USBtoUART
ERROR  11:41:32.981  EZSP Dongle: Unable to open serial port
Unable to communicate with Ember NCP
DEBUG  11:41:32.982  EZSP Dongle: Shutdown
DEBUG  11:41:32.982  EZSP Dongle: Shutdown frameHandler is null
Unable to initialise NCP

**Comment by cdjackson** [comment]
The error is the port is not found.

> jssc.SerialPortException: Port name - /dev/tty.SLAB_USBtoUART; Method name - openPort(); Exception type - Port not found.

**Comment by IgorGanapolsky** [comment]
What does the README say?

**Comment by cdjackson** [comment]
Sorry - I'm not sure I understand what you mean? Can you explain your point please?
